{% set name = "zmq-anyio" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zmq_anyio-{{ version }}.tar.gz
  sha256: c59b7aa761b80f736ee680686e9f4dbad8d7105cf9706e8d8c7a3d6117a35e41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=4.8.0,<5.0.0
    - anyioutils >=0.6.2
    - pyzmq >=26.0.0,<27.0.0

test:
  imports:
    - zmq_anyio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/zmq-anyio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Asynchronous API for ZMQ using AnyIO
  dev_url: https://github.com/davidbrochart/zmq-anyio

extra:
  recipe-maintainers:
    - davidbrochart
