{% set name = "zmq-anyio" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zmq_anyio-{{ version }}.tar.gz
  sha256: 7d30ff2a7a16ff8d3cb648d2f5f664595b7e35e0fa0d9e831cb9b343bc4b449a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=4.8.0,<5.0.0
    - anyioutils >=0.7.1,<0.8.0
    - pyzmq >=26.0.0,<28.0.0

test:
  imports:
    - zmq_anyio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/zmq-anyio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Asynchronous API for ZMQ using AnyIO
  dev_url: https://github.com/davidbrochart/zmq-anyio

extra:
  recipe-maintainers:
    - davidbrochart
